### ISSUE TITLE
.vtt subtitle file problem

### ISSUE THREAD

**Issue by sweetsmile888** [rany2/edge-tts#108]
The Punctuation of the original text in the generated .vtt subtitle file is missing, and many spaces make the text incoheren

**Comment by rany2** [comment]
That's because Microsoft only returns the word without punctuation. In order for this to be fixed, the library needs to somehow restore the punctuation which is not as easy as it sounds. For example, if you input the word `162` the subtitles _sometimes_ would have the word `162` spelled out as `one sixty two`. So as you can see, it's not a very simple issue to solve.
