### ISSUE TITLE
write-subtitles not work

### ISSUE THREAD

**Issue by ltybenet** [rany2/edge-tts#23]
`edge-tts -t "Hello, world!" --write-media hello.mp3 --write-subtitles hello.srt `
The mp3 file is fine, but the srt file is empty

**Comment by rany2** [comment]
It does actually still work. The issue is that the code doesn't automatically set boundary type to 1 when write-subtitles is used. As a temporary workaround you could add `-b 1` to the command line arguments On Nov 18, 2022 7:48 AM, 市井小民 ***@***.***> wrote:
edge-tts -t "Hello, world!" --write-media hello.mp3 --write-subtitles hello.srt 
The mp3 file is fine, but the srt file is empty

**Comment by ltybenet** [comment]
thanks, it worked
