### ISSUE TITLE
that is cannot work now

### ISSUE THREAD

**Issue by ysysdzz** [rany2/edge-tts#51]
that is cannot work now

**Comment by rany2** [comment]
@ysysdzz works fine for me, any details?

**Comment by HubKing** [comment]
> @ysysdzz works fine for me, any details?

Just installed & tested. Works (at least for "hello world"). But I wonder if there is any ban request limit. 

Of course, I am not going to use this other than for my personal use, but I once used non-official Google translation for my own app that I had created only for my personal use, and due to my app's bug I requested several short translation in a quick succession and Google banned my IP. I had to change my IP address to be able to use that library again.

I wonder if this library has a similar limitation (like no consecutive requests within 1 second or something), since this is not MS's official library.

**Comment by rany2** [comment]
I've found it very difficult to get banned. I was only able to get banned after running a few thousand instances at once and the ban only lasted for five minutes.
